CREATE TABLE plugin (id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY, name CHAR(50)) ENGINE=InnoDB;

CREATE TABLE config (id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY, 
    name CHAR(100), 
    value CHAR(100),
    plugin_id integer NOT NULL,
    FOREIGN KEY FK_PLUGIN_ID_PLUGIN(plugin_id) REFERENCES plugin(id) ON DELETE CASCADE
) ENGINE=InnoDB;

